config/routes.rb
Crowdfunder::Application.routes.draw do

	root :to => 'welcome#index'  
  
  resources :projects do
  	resources :pledges, :only => [:create]
  end

  resources :users, :except => [:index, :destroy]
	resource :session, :only => [:new, :create, :destroy]
  
	namespace :my do            # namespace
		resources :projects do    # nested resources
			 	resources :images
		end
	end
 
end

app/models/image.rb
class Image < ActiveRecord::Base
	attr_accessible :file

  belongs_to :project
  
  mount_uploader :file, ImageUploader


end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  attr_accessible :amount

  validates :amount, :presence => true
  validates :amount, :numericality => { :only_integer => true, greater_than: 0 }

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :pledges, :dependent => :destroy
  has_many :images, dependent: :destroy

  attr_accessible :description, :goal, :teaser, :title

  validates :title, :teaser, :description, :presence => true
  validates :goal, :numericality => { :only_integer => true, greater_than: 0 }

  scope :latest, order('created_at DESC')

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  has_many :projects
  has_many :pledges

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :email, :presence => true, :uniqueness => true
  validates :password, :presence => true, :on => :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

	protected

	def not_authenticated
	  redirect_to new_session_path, :alert => "Please login first."
	end

end

app/controllers/my/images_controller.rb
class My::ImagesController < ApplicationController

	before_filter :get_project
	before_filter :require_login

	def index
		@images = @project.images.order(:id)
		@image = @project.images.build
	end

	def create
		@image = @project.images.build(params[:image])
		if @image.save
			redirect_to [:my, @project, :images] # my_project_images_path(@project)
		else
			@images = @project.images.order(:id)
			render :index
		end
	end

	def destroy
		@image = Image.find(params[:id])
    @image.destroy
    redirect_to my_project_images_path, :notice => 'Project was successfully deleted.'
	end

	protected

	def get_project
		@project = Project.find(params[:project_id])
	end

end

app/controllers/my/projects_controller.rb
class My::ProjectsController < ApplicationController

  before_filter :require_login

  def index
    @projects = current_user.projects.latest.page params[:page]
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.build params[:project]
    if @project.save
      redirect_to @project, :notice => "Project successfully created."
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end
    
  def update    
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to @project, :notice => 'Project was successfully updated.'
    else
      render :action => "edit" 
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to my_projects_path, :notice => 'Project was successfully deleted.'
  end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  
  before_filter :require_login 

	def create
  	@project = Project.find(params[:project_id])
  	@pledge = @project.pledges.build params[:pledge]
    @pledge.user = current_user

  	if @pledge.save 
      UserMailer.new_pledge(@pledge).deliver
  		redirect_to @project  
  		flash[:notice] = "Thanks for supporting this project!"
    else
  		render 'projects/show' 
  		#flash[:notice] = "Uups...something went wrong. Try again!"
  	end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
  	@projects = Project.latest.page params[:page]
  end

  def show
  	@project = Project.find(params[:id])
  	@pledge = Pledge.new
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	# Login page
  def new
  end

  # Login submit action
  def create
		@user = login(params[:email], params[:password])
		if @user
			redirect_to :root, :notice => "Welcome back, #{current_user.first_name}!"
		else
			flash.now[:alert] = "Invalid credentials. Try again!"
			render :new
		end
  end

  # Logout submit
  def destroy
		logout
		redirect_to :root, notice: "Bye... Hope to see you later!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
  		auto_login(@user)
  		redirect_to root_path, notice: "Account created."
  	else
  		render :new
  	end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	#Homepage
	def index		
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my/images_helper.rb
module My::ImagesHelper
end

app/helpers/my/projects_helper.rb
module My::ProjectsHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

	def amount_raised
  	amount_raised = 0
  	@project.pledges.each do |pledge|
  		amount_raised += pledge.amount 
  	end
  	number_with_delimiter(amount_raised)
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<div class="navbar">
  <div class="navbar-inner">
   	<%= link_to "CrowdFunder", root_path, :class => "brand" %>
    <ul class="nav">
    	<li class="<%= "active" if controller_name == "welcome" %>"><%= link_to "Home", root_path %></li>
      <li class="<%= "active" if params[:controller] == "projects" %>"><%= link_to "Projects", projects_path %></li>
      <% if logged_in? %>
      	<li class="<%= "active" if params[:controller] == "my/projects" %>"><%= link_to "My Projects", my_projects_path %></li> 
      <% end %>
    </ul>
  
	  <div class="pull-right">
		  <% if logged_in? %>
		    <%= link_to 'Logout', :session, :method => :delete, class: 'btn' %>
		  <% else %>
		    <%= link_to 'Sign Up', [:new, :user], class: 'btn btn-primary' %>
		    <%= link_to 'Sign In', [:new, :session], class: 'btn btn-success' %>
		  <% end %>
		</div>

	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "/layouts/nav" %>

<div class="container">
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>
	
<%= yield %>

</body>
</html>

app/views/my/images/index.html.erb
<h1><%= @project.title %></h1>

<h4>Add Image</h4>

<%= form_for [:my, @project, @image] do |f| %>
	<%= f.file_field :file %>
	<%= f.submit %>
<% end %>

<h4>This project has <%= pluralize(@images.count, "image") %></h4>

<br>

<ul class="thumbnails">
	<% @images.each do |img| %>
		<li class = "span3">
			<a href = "<%= img.file.url %>">
				<img src="<%= img.file.thumb.url %>"></img>
			</div>
		</li>
	<% end %>
</ul>

app/views/my/projects/_form.html.erb
<%= form_for [:my, @project] do |f| %>

  <% unless f.object.errors.empty? %>
    <% if @project.errors.any? %>
  		<div id="error_explanation" class="alert alert-error">
    		<h3><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h3>
			<ul>
    		<% @project.errors.full_messages.each do |msg| %>
      		<li><%= msg %></li>
    		<% end %>
    	</ul>
  		</div>
 		<% end %>
  <% end %>

  <div class="span6">
    <%= f.label :title %>
    <%= f.text_field :title, class: "input-block-level" %>
    <%= f.label :teaser %>
    <%= f.text_field :teaser, class: "input-block-level" %>
    <%= f.label :description %>
    <%= f.text_area :description, class: "input-block-level" %>
    <%= f.label :goal %>
    <%= f.text_field :goal, class: "input-block-level" %>
    
    <div class="form-actions">
      <%= f.submit local_variable, class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/my/projects/edit.html.erb
<h2>Edit your project information</h2>

<br>

<%= link_to "Delete This Project", my_project_path, :method => :delete, :confirm => "Are you sure?", :class => "btn btn-danger" %>

<br>

<%= link_to 'Manage Images', [:my, @project, :images], :class => 'btn btn-small btn-primary' %>

<br>

<%= render 'form', :local_variable => "Edit Project" %>

app/views/my/projects/index.html.erb
<h1 class="offset1">My projects <small><%= page_entries_info @projects %></small></h1>

<br>

<%= link_to "Create New Project", new_my_project_path, :class => "btn btn-primary offset1" %>

<br>

<% @projects.each do |project| %>
	<ul class="offset1">
		<li class = "text-info"><%= link_to project.title, edit_my_project_path(project) %></li>
		<li class = "no-bullet"><%= project.teaser %></li>
	</ul>
<% end %>

<%= paginate @projects %>

app/views/my/projects/new.html.erb
<h2>Create a new project</h2>

<%= render 'form', :local_variable => "Create New Project" %>

app/views/projects/edit.html.erb
<h2>Edit your project information</h2>

<%= form_for @project do |f| %>

  <% unless f.object.errors.empty? %>
    <%= render 'shared/form_errors', :f => f %>
  <% end %>

  <div class="span6">
    <%= f.label :title %>
    <%= f.text_field :title, class: "input-block-level" %>
    <%= f.label :teaser %>
    <%= f.text_field :teaser, class: "input-block-level" %>
    <%= f.label :description %>
    <%= f.text_area :description, class: "input-block-level" %>
    <%= f.label :goal %>
    <%= f.text_field :goal, class: "input-block-level" %>
    
    <div class="form-actions">
      <%= f.submit 'Edit Project', class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/projects/index.html.erb
<h1 class="offset1">Listing projects <small><%= page_entries_info @projects %></small></h1>

<% @projects.each do |project| %>
	<ul class="offset1">
		<li class = "text-info"><%= link_to project.title, project %></li>
		<li class = "no-bullet"><%= project.teaser %></li>
	</ul>
<% end %>

<%= paginate @projects %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<p>A project by <%= @project.user.first_name %> <%= @project.user.last_name %></p>

<!-- amount_raised defined in projects_helper -->
<h3>Total amount raised: <%= amount_raised %></h3> 

<p><%= flash[:notice] %></p>

<%= form_for([@project, @pledge]) do |f| %>
  
  <%= render 'shared/form_errors', :f => f %>

	<div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div>
    <%= f.submit "Pledge Now", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if @pledge.errors.any? %>
  <div id="error_explanation" class="alert alert-error">
    <h3><%= pluralize(@pledge.errors.count, "error") %> prohibited this pledge from being saved:</h3>

    <ul>
    <% @pledge.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
 <% end %>

app/views/users/new.html.erb
<h1>Sign Up for an Account</h1>
<p>Fill in your information below</p>

<hr/>

<%= form_for @user do |f| %>

  <% unless f.object.errors.empty? %>
      <% if @user.errors.any? %>
        <div id="error_explanation" class="alert alert-error">
          <h3><%= pluralize(@user.errors.count, "error") %> prohibited this form from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
  <% end %>
      
  <div class="span6">
    <%= f.text_field :first_name, placeholder: "First Name", class: "input-block-level" %>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "input-block-level" %>
    <%= f.text_field :email, placeholder: "E-mail Address", class: "input-block-level" %>
    <%= f.password_field :password, placeholder: "Password", class: "input-block-level" %>
    <div class="form-actions">
      <%= f.submit 'Create Account', class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>